version: '3.1'

services:
  zookeeper:
    image: zookeeper:3.5.6
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
    volumes:
      - /opt/dockerpub/zookeeper/data:/data
      - /opt/dockerpub/zookeeper/datalog:/datalog
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    restart: always
    depends_on:
      - zookeeper
    expose:
      - "9093"
    ports:
      - "9092:9092"
    volumes:
      - /opt/dockerpub/kafka/:/kafka-data
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:3:1,test.DLT:3:1"
      KAFKA_LOG_DIRS: "/kafka-data"
